### ISSUE TITLE
Simplifier le réimport des données de la région

### ISSUE THREAD

**Issue by n-b** [velo-iledefrance/observatoire-vif#10]
En attente de cocarto; pour l’instant le réimport est à faire à la main en spécifiant les paramètres à chaque fois.

Sur cocarto:
- [x] [Configuration de l’import](https://gitlab.com/CodeursEnLiberte/cocarto/-/issues/305)
  - [x] [MR](https://gitlab.com/CodeursEnLiberte/cocarto/-/merge_requests/602)
- [x] Deuxième point cette issue](https://gitlab.com/CodeursEnLiberte/cocarto/-/issues/306) pour réutiliser le dernier import

**Comment by Tristramg** [comment]
Fait: on peut desormais refaire un import existant et on a mis en place un import quotidien
